### ISSUE TITLE
Bond lines in blade parametrization

### ISSUE THREAD

**Issue by mrosemeier** [FUSED-Wind/fusedwind-dev#22]
I propose to integrate the definition of bond lines into the FUSED-Wind parametrization. The parameters would serve as input for a cross section structure 2D mesher such as shellexpander or any other mesher, as well as for a 3D mesher.

Considering the input data files we would extend the header of the `*.dp3d` files with DPs that enclose the cross sectional area of the trailing edge bond lines (bond00) and spar shell (bond01, bond02) or web spar connections:
```
# version 2
# bond00 bond01 bond02
# 0 1 -2 -1
# 4 5 -6 -5
# -6 -5 4 5
# web00  web01  web02  web03
# -1 0
# 2 -3
# 4 -5
# 5 -6
```

Further, additional  `*_bondXX.st3d` files are required to set the material and the thicknesses at the positions along span. For the trailing edge bond line it is not necessarily required to set the thickness rather than setting a boolean since usually the TE bond line fills the area between the expanded regions.

`*_bond00.st3d` (TE bond line)

```
# version 2
# bond00
# s    adhesive00
0.0 0.0
0.5 1.0
...
0.8 1.0
1.0 0.0
```

`*_bond01.st3d` (Spar shell bond line)

```
# version 2
# bond01
# s    adhesive00 triax00 uniax00 triax01
0.0 0.005 0.002 0.08 0.002
0.5 0.005 0.002 0.08 0.002
...
0.8 0.005 0.002 0.08 0.002
1.0 0.005 0.002 0.08 0.002
```
In case of web spar/ shell spar connections additional layers can be added as well to be used as "web foot".

Let me know if you have any other suggestions!

**Comment by fzahle** [comment]
that sounds like a good addition. if we add a check for the bond%02d keyword existing version1 files would continue to work. 

@pilotmm, we should in this revision of the format also include possible additional parameters that could be useful for you. Any suggestions?

we can also include the change from s -1->1 to s 0->1 in this version.
