### ISSUE TITLE
Transfer of old fusedwind definition classes for regions, layers, etc.

### ISSUE THREAD

**Issue by mrosemeier** [FUSED-Wind/fusedwind-dev#4]
@fzahle 

I haven't found the old fusedwind classes Region3D, Layup3D, BladeStructure3D, etc. I think, it was a nice way to define the layup of the blade. If you don't mind I will transfer these classes.

**Comment by fzahle** [comment]
in the old FUSED-Wind we used VariableTree objects to define and group variables, and then use these in the different components/assemblies, which made it easy to refer to one place on how all I/O was defined. In the new OpenMDAO the VariableTree class is gone, and defining variables inside an object like the VariableTree will cause OpeNMDAO to look at it as a non-differentiable quantity (pass_by_obj). Also, so far, OpenMDAO has only been able to communicate data of type float/array in parallel.

Therefore we've chosen to define variables in a very flat way, using simple floats and arrays. You can see how the variables are created in e.g. `SplinedBladeStructure` where based on the dictionary input defining the structure (constructed by `read_bladestructure` based on an input file), the full blade structure definition corresponding to the old `Region3D`, `Layup3D`, `BladeStructure3D` is created. Layer thicknesses are defined in e.g. `r04uniaxT, region division points in the array `DPs` etc. Some quantities that are static, such as material names and web connectivity, are not passed around as params visible to OpenMDAO, but simply pass them to the classes that need them when instantiating them. In for example BECASWrapper you can see how we construct corresponding inputs to those created in `SplinedBladeStructure` with identical names allowing for the automatic connection of variables in OpenMDAO.

we're still thinking about how to make the interfaces visible to users, and what we will probably do is to define the variables in a programming language agnostic format such as Yaml og JSON. But this will only be on the I/O level, and not affect how we pass data around in the code.

Hope this makes sense!

**Comment by mrosemeier** [comment]
Yes, makes sense. The yaml / json idea is probably a good one if you have a reasonable amount of data to define.

My proposal was indeed pointing to an initial I/O functionality: If you start from scratch defining a new blade then you don't have neither the input files `*.dp3d` and `*.st3d` nor the `st3d` dictionary. If you don't want to write these files or the dict by hand you need some code to do it as shown in th [old style](https://github.com/FUSED-Wind/fusedwind/blob/develop/src/fusedwind/test/test_bladestructure.py). The idea is to transfer the old objects into pure python to allow this functionality for initial parametrization that can create the `st3d` dict. With the `write_bladestructure` you can then also write the `*.dp3d` and `*.st3d` files.

What do you think?

**Comment by fzahle** [comment]
sounds like a good idea to re-establish that functionality. What we'd also like to implement is an easier way to define the structure from scratch based on more intuitive positioning of the DPs, e.g. percentage chord or offset relative to main axis, width and angle of the spar cap. together this your suggestion this would form a nice pre-processing script for setting up the more abstracted parameterised blade normalised according to surface fraction that we use in optimisations.

If you want to add the functionality you suggested for defining material props, layer thicknesses etc, that would be great. Then we will add the positioning of DPs, since we already have some pieces of code that pretty much achieves this.

**Comment by mrosemeier** [comment]
We have a module in development that can define the DPs on the surface intersecting with vertical planes and curved planes (i.e. for swept blades) used for webs and spar caps. It is actually using the functionality in old fusedwind I am requesting here and needs to be adapted accordingly. After that we could have a review of the functionalities and merge them with yours.

**Comment by fzahle** [comment]
that sounds great!

**Comment by fzahle** [comment]
this has now been merged, so this issue can be closed.
