### ISSUE TITLE
Naming convention for layers within a region

### ISSUE THREAD

**Issue by mrosemeier** [FUSED-Wind/fusedwind-dev#6]
The layers within a region are currently named so that if the region contains a material twice, the first occurrence is named 'triax' and the second occurrence gets the name 'triax01'. Would it be problematic if we call the first layer 'triax00' to be consistent with DP and region naming conventions?

**Comment by fzahle** [comment]
I agree, that isn't consistent. we would welcome a pull request with that change :-) I don't know whether the tests in there now will catch all the places where this is relevant, but give it a go and we'll fix things as we catch them.
